import pprint

class WriterAgent:
    def __init__(self):
        self.system_prompt = (
            "You are the Writer, a skilled communicator. Your task is to synthesize the research and analysis into a "
            "clear, engaging, and well-structured report. Use a professional yet approachable tone. Make sure the "
            "report is easy to understand and visually appealing. Do not add new facts—only use what the team has "
            "provided."
        )

    def _format_research_human(self, research):
        """Format research findings as a human-readable summary."""
        if isinstance(research, dict) and 'results' in research and isinstance(research['results'], list):
            lines = []
            for idx, item in enumerate(research['results'], 1):
                title = item.get('title') or item.get('content', '').split('\n')[0][:80]
                summary = item.get('content', '').replace('\n', ' ').strip()
                source = item.get('url') or item.get('source')
                if title:
                    lines.append(f"- **{title}**")
                if summary:
                    lines.append(f"  {summary}")
                if source:
                    lines.append(f"  [Source]({source})")
                lines.append("")
            return '\n'.join(lines)
        # fallback
        return str(research)

    def write_report(self, research, analysis):
        """Synthesize research and analysis into a polished final report with both human and raw data sections."""
        # Human-readable research summary
        research_human = self._format_research_human(research)
        # Raw data pretty-printed
        research_raw = pprint.pformat(research, indent=2) if isinstance(research, (dict, list)) else str(research)

        report = f"# OrchestrateAI Research Report\n\n"
        report += "This report provides a comprehensive overview based on the initial query, combining automated web research with data analysis. Below are the key findings and their corresponding analysis.\n\n"
        report += f"## 1. Research Findings (Summary)\n\n"
        report += research_human + "\n\n"
        report += f"## 2. Analysis\n\n"
        report += "The Analyst agent processed the research data, yielding the following insights:\n\n"
        report += f"```\n{analysis}\n```\n\n"

        report += f"---\n\n## Appendix: Raw Research Data\n\n"
        report += f"```json\n{research_raw}\n```\n\n"
        report += "*This report was automatically generated by the OrchestrateAI multi-agent system.*"
        return report   