import pprint

class WriterAgent:
    def __init__(self):
        pass

    def write_report(self, research, analysis):
        """Synthesize research and analysis into a polished final report."""
        
        # Ensure the research data is nicely formatted as a multi-line string
        # pprint.pformat() is perfect for this. It formats data and returns a string.
        if isinstance(research, (dict, list)):
            research_formatted = pprint.pformat(research, indent=2)
        else:
            research_formatted = str(research)

        # Start with a title and introduction
        report = f"# OrchestrateAI Research Report\n\n"
        report += "This report provides a comprehensive overview based on the initial query, combining automated web research with data analysis. Below are the key findings and their corresponding analysis.\n\n"
        
        # Add the Research section with the newly formatted string
        report += f"## 1. Research Findings\n\n"
        report += "The Researcher agent gathered the following information from the web:\n\n"
        report += f"```json\n{research_formatted}\n```\n\n"
        
        # Add the Analysis section
        report += f"## 2. Analysis\n\n"
        report += "The Analyst agent processed the research data, yielding the following insights:\n\n"
        report += f"```\n{analysis}\n```\n\n"
        
        # Conclude the report
        report += "---\n\n"
        report += "*This report was automatically generated by the OrchestrateAI multi-agent system.*"
        
        return report